// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: service_bank_app.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransferResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*CreateTransferResult_Response
	//	*CreateTransferResult_ErrorResponse
	Result isCreateTransferResult_Result `protobuf_oneof:"result"`
}

func (x *CreateTransferResult) Reset() {
	*x = CreateTransferResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_bank_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResult) ProtoMessage() {}

func (x *CreateTransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_bank_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResult.ProtoReflect.Descriptor instead.
func (*CreateTransferResult) Descriptor() ([]byte, []int) {
	return file_service_bank_app_proto_rawDescGZIP(), []int{0}
}

func (m *CreateTransferResult) GetResult() isCreateTransferResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *CreateTransferResult) GetResponse() *CreateTransferResponse {
	if x, ok := x.GetResult().(*CreateTransferResult_Response); ok {
		return x.Response
	}
	return nil
}

func (x *CreateTransferResult) GetErrorResponse() *CreateTransferErrorResponse {
	if x, ok := x.GetResult().(*CreateTransferResult_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

type isCreateTransferResult_Result interface {
	isCreateTransferResult_Result()
}

type CreateTransferResult_Response struct {
	Response *CreateTransferResponse `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type CreateTransferResult_ErrorResponse struct {
	ErrorResponse *CreateTransferErrorResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

func (*CreateTransferResult_Response) isCreateTransferResult_Result() {}

func (*CreateTransferResult_ErrorResponse) isCreateTransferResult_Result() {}

type GetAccountResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GetAccountResult_Response
	//	*GetAccountResult_ErrorResponse
	Result isGetAccountResult_Result `protobuf_oneof:"result"`
}

func (x *GetAccountResult) Reset() {
	*x = GetAccountResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_bank_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResult) ProtoMessage() {}

func (x *GetAccountResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_bank_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResult.ProtoReflect.Descriptor instead.
func (*GetAccountResult) Descriptor() ([]byte, []int) {
	return file_service_bank_app_proto_rawDescGZIP(), []int{1}
}

func (m *GetAccountResult) GetResult() isGetAccountResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetAccountResult) GetResponse() *GetAccountResponse {
	if x, ok := x.GetResult().(*GetAccountResult_Response); ok {
		return x.Response
	}
	return nil
}

func (x *GetAccountResult) GetErrorResponse() *GetAccountErrorResponse {
	if x, ok := x.GetResult().(*GetAccountResult_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

type isGetAccountResult_Result interface {
	isGetAccountResult_Result()
}

type GetAccountResult_Response struct {
	Response *GetAccountResponse `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type GetAccountResult_ErrorResponse struct {
	ErrorResponse *GetAccountErrorResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

func (*GetAccountResult_Response) isGetAccountResult_Result() {}

func (*GetAccountResult_ErrorResponse) isGetAccountResult_Result() {}

var File_service_bank_app_proto protoreflect.FileDescriptor

var file_service_bank_app_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61,
	0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x19, 0x72, 0x70,
	0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4,
	0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x48, 0x0a, 0x0e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x98, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x8f, 0x01, 0x0a, 0x07, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x70, 0x70, 0x12, 0x47, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x19,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x41, 0x70, 0x65, 0x73, 0x4a, 0x73, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2d, 0x61, 0x70, 0x70,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_bank_app_proto_rawDescOnce sync.Once
	file_service_bank_app_proto_rawDescData = file_service_bank_app_proto_rawDesc
)

func file_service_bank_app_proto_rawDescGZIP() []byte {
	file_service_bank_app_proto_rawDescOnce.Do(func() {
		file_service_bank_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_bank_app_proto_rawDescData)
	})
	return file_service_bank_app_proto_rawDescData
}

var file_service_bank_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_bank_app_proto_goTypes = []interface{}{
	(*CreateTransferResult)(nil),        // 0: pb.CreateTransferResult
	(*GetAccountResult)(nil),            // 1: pb.GetAccountResult
	(*CreateTransferResponse)(nil),      // 2: pb.CreateTransferResponse
	(*CreateTransferErrorResponse)(nil), // 3: pb.CreateTransferErrorResponse
	(*GetAccountResponse)(nil),          // 4: pb.GetAccountResponse
	(*GetAccountErrorResponse)(nil),     // 5: pb.GetAccountErrorResponse
	(*CreateTransferRequest)(nil),       // 6: pb.CreateTransferRequest
	(*GetAccountRequest)(nil),           // 7: pb.GetAccountRequest
}
var file_service_bank_app_proto_depIdxs = []int32{
	2, // 0: pb.CreateTransferResult.response:type_name -> pb.CreateTransferResponse
	3, // 1: pb.CreateTransferResult.error_response:type_name -> pb.CreateTransferErrorResponse
	4, // 2: pb.GetAccountResult.response:type_name -> pb.GetAccountResponse
	5, // 3: pb.GetAccountResult.error_response:type_name -> pb.GetAccountErrorResponse
	6, // 4: pb.BankApp.CreateTransfer:input_type -> pb.CreateTransferRequest
	7, // 5: pb.BankApp.GetAccount:input_type -> pb.GetAccountRequest
	0, // 6: pb.BankApp.CreateTransfer:output_type -> pb.CreateTransferResult
	1, // 7: pb.BankApp.GetAccount:output_type -> pb.GetAccountResult
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_bank_app_proto_init() }
func file_service_bank_app_proto_init() {
	if File_service_bank_app_proto != nil {
		return
	}
	file_rpc_create_transfer_proto_init()
	file_rpc_get_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_bank_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTransferResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_bank_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_bank_app_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CreateTransferResult_Response)(nil),
		(*CreateTransferResult_ErrorResponse)(nil),
	}
	file_service_bank_app_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetAccountResult_Response)(nil),
		(*GetAccountResult_ErrorResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_bank_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_bank_app_proto_goTypes,
		DependencyIndexes: file_service_bank_app_proto_depIdxs,
		MessageInfos:      file_service_bank_app_proto_msgTypes,
	}.Build()
	File_service_bank_app_proto = out.File
	file_service_bank_app_proto_rawDesc = nil
	file_service_bank_app_proto_goTypes = nil
	file_service_bank_app_proto_depIdxs = nil
}
